#!/usr/bin/env python3

cfg = dict(
    model_type='enet',
    momentum=0.9,
    n_cats=12,
    num_aux_heads=4,
    lr_start=1e-2,
    weight_decay=1e-4,
    warmup_iters=1000,
    max_iter=20000,
    dataset='ENetCamVid',
    im_root='/home/ethan/data/ethan/data/SegNet-Tutorial/CamVid',
    train_im_anns='./datasets/cityscapes/train.txt',
    val_im_anns='./datasets/cityscapes/val.txt',
    scales=[0.25, 2.],
    cropsize=[360, 480],
    eval_crop=[720, 960],
    eval_scales=[0.5, 0.75, 1.0, 1.25, 1.5, 1.75],
    ims_per_gpu=16,
    eval_ims_per_gpu=1,
    use_fp16=True,
    use_sync_bn=True,
    respth='./res',
)
